### ISSUE TITLE
benchmark.json: No such file or directory

### ISSUE THREAD

**Issue by Kixunil** [BurntSushi/critcmp#11]
**Description**
`critcmp`terminates with message:
```
/home/user/rust-prometheus/target/criterion/concurrent_observe_and_collect/new: benchmark.json: No such file or directory (os error 2)
```

**Steps to reproduce**
1. `git clone https://github.com/tikv/rust-prometheus`
2. `cd https://github.com/tikv/rust-prometheus`
3. `$ cargo +stable bench --bench text_encoder -- --save-baseline baseline1`
4. `$ cargo +stable bench --bench text_encoder -- --save-baseline baseline2`
5. `critcmp baseline1 baseline2`

**Versions**
`criterion` 0.3.3
`critcmp` 0.1.4 (installed today)

**Comment by BurntSushi** [comment]
I can't reproduce:

```
$ critcmp baseline1 baseline2
group                            baseline1                              baseline2
-----                            ---------                              ---------
text_encoder_with_escaping       1.01     85.5±2.06ms        ? B/sec    1.00     85.0±8.58ms        ? B/sec
text_encoder_without_escaping    1.00     62.0±1.60ms        ? B/sec    1.00     61.9±3.12ms        ? B/sec
```

My _guess_ is that your `target/criterion` directory contains data generated by older versions of Criterion maybe? If so, critcmp will likely choke on it.

**Comment by Kixunil** [comment]
Retried from the clean and it works now. Probably just a fluke. Thanks for hint!

```
$ cargo +stable tree | grep criterion
├── criterion v0.3.3
│   ├── criterion-plot v0.4.3
```
