### ISSUE TITLE
Internal file format changes

### ISSUE THREAD

**Issue by bheisler** [BurntSushi/critcmp#5]
Hey, this is just a heads-up that the internal file formats used by Criterion.rs will be changing in the next release. Specifically, `sample.json` and `estimates.json`. Since they are internal files I don't consider this a breaking change, but I thought I'd let you know so you can update critcmp.

New `sample.json` format contains one `SavedSample`:
```
pub(crate) enum ActualSamplingMode {
    Linear,
    Flat,
}
pub(crate) struct SavedSample {
    sampling_mode: ActualSamplingMode,
    iters: Vec<f64>,
    times: Vec<f64>,
}
```

New `estimates.json` format contains one `Estimates`:
```
pub struct ConfidenceInterval {
    pub confidence_level: f64,
    pub lower_bound: f64,
    pub upper_bound: f64,
}
pub struct Estimate {
    pub confidence_interval: ConfidenceInterval,
    pub point_estimate: f64,
    pub standard_error: f64,
}
pub struct Estimates {
    pub mean: Estimate,
    pub median: Estimate,
    pub median_abs_dev: Estimate,
    pub slope: Option<Estimate>,
    pub std_dev: Estimate,
}
```

I should also mention that [cargo-criterion](https://github.com/bheisler/cargo-criterion) has its own completely separate file structure using CBOR instead of JSON. It's getting pretty late here so I'll let you get the structure for that from the code.

**Comment by zeeshanlakhani** [comment]
@bheisler would this be related to this new error I'm seeing when running `critcmp --export changes > bench-runs/changes.json` via criterion 0.3.3 (versioned as 0.3 in our code):

```
/home/capsule/bench/target/criterion/mbuf__alloc_vs_alloc_bulk/mbuf__alloc_bulk/changes: estimates.json: missing field `Mean` at line 1 column 982
root@buster:/home/capsule/bench
```

Thanks.

**Comment by bheisler** [comment]
Probably related, yes.
