### ISSUE TITLE
Capitalization issues in estimates.json -- "mean" instead of "Mean"

### ISSUE THREAD

**Issue by sezna** [BurntSushi/critcmp#7]
Hi, I'm having a great time using `critcmp` and really appreciate the tool. I'm running into an issue setting it up on a new computer.

I'm on criterion 0.3.0 and critcmp 0.1.3. My criterion bench outputs the following JSON:

```
{"mean":{"confidence_interval":{"confidence_level":0.95,"lower_bound":98271422.4,"upper_bound":100928456.67},"point_estimate":99591700.17,"standard_error":688684.1673855595},"median":{"confidence_interval":{"confidence_level":0.95,"lower_bound":97666752.0,"upper_bound":101350337.0},"point_estimate":99418969.0,"standard_error":1107511.4378777498},"median_abs_dev":{"confidence_interval":{"confidence_level":0.95,"lower_bound":5462559.542620182,"upper_bound":8502608.17899852},"point_estimate":7297799.626538157,"standard_error":777802.4484694396},"slope":null,"std_dev":{"confidence_interval":{"confidence_level":0.95,"lower_bound":5741768.515991534,"upper_bound":7863115.64418664},"point_estimate":6824751.598088472,"standard_error":548632.199575996}}

```

Critcmp seems to be looking for values with capitalized letters though, and outputs this:
```
estimates.json: missing field `Mean` at line 1 column 753
```

If I then change `mean` to `Mean` in the above JSON, critcmp does this:
```
estimates.json: missing field `Median` at line 1 column 753
```

This continues until I've renamed all the necessary fields. Is there an option I'm missing in either Criterion or critcmp? I'm not sure what's causing this.

Thanks,
Alex

**Comment by BurntSushi** [comment]
Can you try `critcmp 0.1.4`? I just released it. I think this PR should fix what you're seeing: https://github.com/BurntSushi/critcmp/pull/6

The main problem here, as documented in the README, is that critcmp depends on data that Criterion emits with no stable format, so critcmp will always be inherently unstable in that respect. The best thing to do in situations like that:

1. Build from master and see if that works.
2. Check open PRs and see if it's fixed.
3. Fix it yourself and submit a PR.
4. If none of that works, either abandon using critcmp or rollback (or upgrade) Criterion.

Tis the nature of relying on unstable stuff. I see no way around it.

**Comment by sezna** [comment]
Hi Burntsushi,

0.1.4 works. Thanks. As I had my version of criterion pinned to 0.3.0, I thought perhaps it had not changed, but I can see that even that is not always the case. 

Thanks for your response. 

Alex

**Comment by sharksforarms** [comment]
["The JSON files are all considered private implementation details of Criterion.rs, and their structure may change at any time without warning."](https://bheisler.github.io/criterion.rs/book/user_guide/csv_output.html)

~:)~

~https://github.com/BurntSushi/critcmp/pull/8~
